rule.reader=database
db.rule.table=RULE_DEFINE_INFO
db.accesser=tech.kiwa.engine.utility.DirectDBAccesser
#tech.kiwa.engine.utility.SpringDBAccesser
jdbc.driver=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://119.31.210.118:3306/base_framework?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
jdbc.username=root
#jdbc.password=5WTqQ@TwDN%C
jdbc.password=fgJwICw0gQCGKxats1dBjiHCl3HqW8hCecRw9Bf7ny2vThflvbC06reGWiWYO4H0fSot83Jj94hwSK+EMaEJcQ==
jdbc.publickey=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAJbP9dxzrrPWsm/POZjfg3pGZ13bSN1SDRvwxFwBYZxTG0Qy/A8Kn/WivS7C4TIRsZBKWXEkiHJvB+lYjlHq0+sCAwEAAQ==
#db.accesser=com.tpfh.fintech.modules.rule.config.TpfhDBAccesser
